### ISSUE TITLE
Problem: Incorrect object passed to Command class init during normalization

### ISSUE THREAD

**Issue by camlyall** [artefactual-labs/a3m#336]
FP Rule passed to Command object 'job' variable

Reference:
https://github.com/artefactual-labs/a3m/blob/6431c8c4796dc794e41e59ffcbd003f91dc4a230/a3m/client/clientScripts/normalize.py#L473

Command object init:
https://github.com/artefactual-labs/a3m/blob/6431c8c4796dc794e41e59ffcbd003f91dc4a230/a3m/client/clientScripts/normalize.py#L27-L44

Correct reference:
`cl = Command(job, command, replacement_dict, once_normalized_callback(job), opts)`

**Comment by sevein** [comment]
@camlyall let me know if I should close this, I won't have time to test!

**Comment by camlyall** [comment]
@sevein yep just tested and normalization premis event is present. all good to close
