### ISSUE TITLE
Problem: "test" PREMIS Agent included in METS file

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-labs/a3m#346]
The METS file written by a3m currently contains two default PREMIS Agents:

```
<mets:digiprovMD ID="digiprovMD_57">
  <mets:mdWrap MDTYPE="PREMIS:AGENT">
    <mets:xmlData>
      <premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
        <premis:agentIdentifier>
          <premis:agentIdentifierType>preservation system</premis:agentIdentifierType>
          <premis:agentIdentifierValue>a3m (unknown version)</premis:agentIdentifierValue>
        </premis:agentIdentifier>
        <premis:agentName>a3m</premis:agentName>
        <premis:agentType>software</premis:agentType>
      </premis:agent>
    </mets:xmlData>
  </mets:mdWrap>
</mets:digiprovMD>
<mets:digiprovMD ID="digiprovMD_58">
  <mets:mdWrap MDTYPE="PREMIS:AGENT">
    <mets:xmlData>
      <premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
        <premis:agentIdentifier>
          <premis:agentIdentifierType>repository code</premis:agentIdentifierType>
          <premis:agentIdentifierValue>test</premis:agentIdentifierValue>
        </premis:agentIdentifier>
        <premis:agentName>test</premis:agentName>
        <premis:agentType>organization</premis:agentType>
      </premis:agent>
    </mets:xmlData>
  </mets:mdWrap>
</mets:digiprovMD>
```

Both of these agents are also included in each PREMIS Event created by A3M as "linkingAgents":

```
<premis:linkingAgentIdentifier>
  <premis:linkingAgentIdentifierType>preservation system</premis:linkingAgentIdentifierType>
  <premis:linkingAgentIdentifierValue>a3m (unknown version)</premis:linkingAgentIdentifierValue>
</premis:linkingAgentIdentifier>
<premis:linkingAgentIdentifier>
  <premis:linkingAgentIdentifierType>repository code</premis:linkingAgentIdentifierType>
  <premis:linkingAgentIdentifierValue>test</premis:linkingAgentIdentifierValue>
</premis:linkingAgentIdentifier>
```

**Problem**
A "test" PREMIS Agent is included in the METS file, but doesn't add any useful information.

**Expected outcome**
The "test" agent should not be included in the METS file as a PREMIS Agent or a linking Agent in PREMIS Events.

**Comment by joel-simpson** [comment]
We could also frame this issue as "problem: a3m users are not able to set PREMIS agent". Ideally an a3m user would be able to set / define (somehow) the PREMIS agent for their institution in the way that it can be set in Archivematica ([see documentation here](https://www.archivematica.org/en/docs/archivematica-1.13/admin-manual/installation-setup/customization/dashboard-config/#premis-agent)). 

a minor related issue I'll just note here is that it would be nice if the a3m agent actually provided version number (not "_a3m (unknown version)_"

**Comment by sallain** [comment]
After some discussion, we'd like to continue to have two PREMIS agents - one for the software and one for the organization.

For the software agent, the existing agent is more or less fine - pulling the version number from the code to replace `(unknown version)` would be great. The software agent should always be used in the METS.

```
<premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
    <premis:agentIdentifier>
        <premis:agentIdentifierType>preservation system</premis:agentIdentifierType>
        <premis:agentIdentifierValue>a3m (v. 0.5.0)</premis:agentIdentifierValue>
    </premis:agentIdentifier>
    <premis:agentName>a3m</premis:agentName>
    <premis:agentType>software</premis:agentType>
</premis:agent>
```

For the organization agent, we can hardcode two of the controlled vocab values (agentIdentifierType and agentType). The other two should be set by the organization on deployment.

```
<premis:agent xmlns:premis="http://www.loc.gov/premis/v3" xsi:schemaLocation="http://www.loc.gov/premis/v3 http://www.loc.gov/standards/premis/v3/premis.xsd" version="3.0">
    <premis:agentIdentifier>
        <premis:agentIdentifierType>local [hardcoded]</premis:agentIdentifierType>
        <premis:agentIdentifierValue>Organization Name (or controlled vocabulary value per 3.1.2 agentIdentifierValue) </premis:agentIdentifierValue>
    </premis:agentIdentifier>
    <premis:agentName>Organization Name</premis:agentName>
    <premis:agentType>organization [hardcoded]</premis:agentType>
</premis:agent>
```

If the organization agent is not configured, it can be dropped from the METS.

**Comment by camlyall** [comment]
We previously discussed the inclusion of the agentIdentifierValue and agentName values as optional command line arguments. Initially, I envisioned it to look something like this:
`a3m.cli.client --name=test_transfer --orgAgentIdentifierValue=OrgName --agentName=OrgName`

However, this approach would make the core command line arguments extensive as we add more user-defined Premis variables. I did consider the possibility of incorporating them into the Processing Config key-value pair options, but that wouldn't align with Archivematica processing configurations and doesn't contribute to the archiving process. For example:
`--processing-config="orgAgentIdentifierValue=OrgName"`

A better solution might be to develop a new group called "Premis Options" with key-value pairs, such as:
`--premis-options="orgAgentIdentifierValue=OrgName"`

This approach would allow for the extension of Premis variables without increasing the core command line arguments.
```
Options:
--name NAME
                                Name of the package.

--address ADDRESS
                                a3m server address (form "host:port"), e.g.: "172.26.30.2:12345".

--wait-for-ready
                                Block until the server becomes available.

-p, --processing-config CONFIG_PAIR
                                Processing configuration pair (form "name:value"), e.g.: "normalize=no".

--premis-options CONFIG_PAIR
                                Premis options pair (form "name:value"), e.g.: "premisAgentName=OrgName".

--no-input
                                Disable interactive mode.

--help Show this message and exit.
```

**Comment by djjuhasz** [comment]
@camlyall I'm having a hard time imagining any other PREMIS entities that we would want to set in the config, do you have any specific use-cases in mind?  

I'm also thinking that key value pairs might be too limiting to represent the structure of PREMIS data.  On the other hand it seems like overkill to pass full XML formatted PREMIS data, e.g.

````
a3m.cli.client --name=test_transfer --org-agent="<premis:agentIdentifier><premis:agentIdentifierType>local</premis:agentIdentifierType><premis:agentIdentifierValue>Organization Name</premis:agentIdentifierValue></premis:agentIdentifier><premis:agentName>Organization Name</premis:agentName><premis:agentType>organization</premis:agentType>"
```

Maybe passing JSON data would be a good compromise in this case? E.g.

```
a3m.cli.client --name=test_transfer --orgAgent={"agentIdentifier: {"agentIdentifierType": "local", "agentIdentifierValue": "Organization Name"}, "agentName": "Organization Name", "agentType": "organization"}
```

Another possible option is for "--org-agent" to take a filepath, and the data could be set in the file, which could be formatted with XML, JSON, or something else (e.g. YAML).

Can the "processing-config" values currently be set in a config file or via environment variables?  It would be nice to have the option to use a config file instead of CLI flags.

Sorry, that's a lot of ideas to throw at you, especially since I'm leaving tomorrow for vacation.  Hopefully you, @sallain and the other devs can make a decision about which way to go.

**Comment by sevein** [comment]
One issue with CLI flags is that we have two (or three) so you may want to accept the same flag in both modules. The flags accepted by the client are specific to a specific transfer request as opposed to the a3m general configuration. These are the entry points:
- `a3m.cli.client` can operate both in standalone mode (embeds a server) or as a client to an external server (`--address=host:port`), and
- `a3m.cli.server` launches the a3m server only.

The main configuration source at the moment is `a3m/settings/common.py`, which is inherited from Archivematica and Django. That module is an application asset that is distributed with a3m and it provides defaults but it is also asked to load configuration from other sources. This is the snippet that controls how the configuration is loaded:

```python
config = Config(env_prefix="A3M", attrs=CONFIG_MAPPING)
config.read_defaults(StringIO(CONFIG_DEFAULTS))
config.read_files(["/etc/a3m/a3m.cfg"])
config.read_dict(_get_data_dir_defaults(config))
```

So probably the most sensible thing at the moment is to add the new fields with defaults to the common.py module. That would allow for setting them via `/etc/a3m/a3m.cfg` or environment strings following the `A3M_*` pattern right away. With that I think next would be ensuring that these values are written to the database. I think that would need to happen somewhere [here](https://github.com/artefactual-labs/a3m/blob/233fdd6a8c899918188c9a67d89db976d9e03323/a3m/server/db.py#L110).

Long-term it'd be nice if the agent was a request-scoped value. That'd be defined here in our API: https://github.com/artefactual-labs/a3m/blob/233fdd6a8c899918188c9a67d89db976d9e03323/proto/a3m/api/transferservice/v1beta1/request_response.proto#L9-L13, but we would need to do some refactoring to honour them.

**Comment by camlyall** [comment]
@djjuhasz We spoke about the potential of allowing the <premis:agentType> to be configured but for now we just hardcode it. But on reflection perhaps organisation is the only agentType that requires configuration from the user...

@sevein I understand what you're getting at. It makes more sense to apply the premis config to the server module as opposed to the client as organisations aren't likely to share a3m servers. Perhaps the client premis config could override the server premis config for unique situations (unsure of complexity of this). It certainly makes sense to accept the config in both modules for cases where the embeded server is used.
I have been working with [request_response.proto](https://github.com/artefactual-labs/a3m/blob/233fdd6a8c899918188c9a67d89db976d9e03323/proto/a3m/api/transferservice/v1beta1/request_response.proto#L9-L13) and am working on refactoring.
Example:
```
message SubmitRequest {
	string name = 1;
	string url = 2;
	ProcessingConfig config = 3;
	PremisAgentConfig premis = 4;
}
...
message PremisAgentConfig {
	string agent_identifier_value = 1;
	string agent_name = 2;
}
```

**Comment by sevein** [comment]
If we update `a3m/settings/common.py` then we should be able to inject config via `/etc/a3m/a3m.cfg` and/or environment strings. I think that the challenge here is to populate those values in the database. Right now I believe the defaults are just part of the initial database fixture here: https://github.com/search?q=repo%3Aartefactual-labs%2Fa3m%20%22unknown%20version%22&type=code. Hopefully the migrate function in db.py can take care of that.
I believe this would benefit both `a3m.cli.server` and `a3m.cli.client`.
To be clear, the idea of using CLI flags may work but I don't think it's as straightforward. When deploying a3m in k8s we're going to be passing config via environment strings or a3m.cfg anyways, so it's not a big deal.
Request-scoped config (i.e. proto files) would be a nice to have but I would also not worry about that right now.

**Comment by camlyall** [comment]
Fixed in https://github.com/artefactual-labs/a3m/pull/350

Issue can be closed
