### ISSUE TITLE
Use name of transfer directory as AIP name

### ISSUE THREAD

**Issue by sallain** [artefactual-labs/a3m#352]
**Is your feature request related to a problem? Please describe.**

It is difficult to differentiate between AIPs, because all AIPs are entitled `enduro-[UUID]`.

**Describe the solution you'd like**

Replace the prefix `enduro` with the name of the transfer package. If my transfer package is titled `SAPILA73.zip`, the resulting AIP should be titled `SAPILA73-[UUID]`.

**Describe alternatives you've considered**

**Additional context**

**Comment by sevein** [comment]
This was an issue in enduro (already solved), not a3m.
