### ISSUE TITLE
Problem: Scan for viruses still appears as a job

### ISSUE THREAD

**Issue by sallain** [artefactual-labs/a3m#394]
**Describe the bug**

a3m's list of preservation tasks includes "Scan for viruses", and after you have created an AIP the job is listed in Enduro with the status of Done. However, a3m doesn't actually do virus scanning (ClamAV has been removed), so this is misleading. The job should not appear in Enduro.

**To Reproduce**

1. Create an AIP in a3m
2. Check the Create AIP preservation actions and find `Scan for viruses`

**Expected behavior**
Artifacts of virus scanning should be removed from a3m and the job should not appear in Enduro.

**Screenshots**

![image](https://github.com/artefactual-labs/a3m/assets/4612276/d070a440-67c5-439b-a760-3e1d04f47ceb)

**Comment by sevein** [comment]
I think that we have two options:
1. We entirely remove antivirus jobs from workflow and related client scripts, or
2. We port the work done in Archivematica to make antivirus optional via processing config (https://github.com/artefactual/archivematica/commit/c37d5af3edcf757670c4bd03f3c9a29b8e2cc73c) - this won't fix the fact that a3m can't talk to clamav, but it leaves the option open just in case in the future we explore other ways to do virus scanning.

**Comment by sallain** [comment]
@sevein thanks for these options!

I think it needs to be abundantly clear that the system, as we currently deploy it, does not do virus scanning. We could maybe achieve this by removing any user-facing mention of it, but that seems a bit hacky?

I really don't know if we'll want to reintroduce virus scanning in the future. In my opinion, virus scanning is something that should be done by an organization when they receive the digital materials - well before they are introduced to the preservation system. I could maybe see an organization wanting to do a second scan as part of a pre-processing workflow, or as a step prior to transfer to the preservation system.

I'm not ready to say "no virus scanning", yet, as we see how the systems evolve, but that's my current thinking. As such, option 1 would be my preferred choice. If we do decide that virus scanning has a place in the preservation system, I'd almost rather build it from the ground up.
